import type { Context } from "./ui-context";
import { createPage } from "./ui-page";
export const inject = ["slots", "host", "styles", "ui"];
export function apply(ctx: Context) {
  ctx.styles(
    '.sm-page{margin:0;padding:0;width:100%;box-sizing:border-box}.sm-stack{display:flex;flex-direction:column;gap:16px}.sm-row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.sm-title{flex:1;min-width:0;overflow-wrap:anywhere}.sm-toolbar{gap:12px}.sm-toolbar>[role=combobox]{width:auto;min-width:160px;max-width:100%}.sm-controls{margin-left:auto}.sm-ready{font-size:12px;color:var(--muted-foreground);display:inline-flex;align-items:center;gap:6px}.sm-ready:before{content:"";width:5px;height:5px;border-radius:50%;background:var(--color-emerald-500,#10b981)}.sm-tabs{display:flex;gap:20px;border-bottom:1px solid var(--border)}.sm-page .sm-tab{border-radius:0;border-bottom:2px solid transparent;padding:10px 0;height:auto;background:transparent;color:var(--muted-foreground)}.sm-page .sm-tab[aria-pressed=true]{border-bottom-color:var(--foreground);color:var(--foreground)}.sm-empty{padding:40px 0;text-align:center;color:var(--muted-foreground);font-size:14px}.sm-pagination{justify-content:flex-end;font-size:13px}.sm-search{display:flex;gap:8px;flex:1;min-width:180px}.sm-card{border:1px solid var(--border);border-radius:10px;padding:16px}.sm-list{list-style:none;margin:0;padding:0}.sm-item{padding:16px 0;border-bottom:1px solid var(--border)}.sm-item:first-child{border-top:1px solid var(--border)}.sm-excerpt{white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0}.sm-source{font-size:13px;overflow-wrap:anywhere;opacity:.7}.sm-stack label{display:grid;gap:6px}@media(max-width:600px){.sm-toolbar{gap:8px}.sm-search{flex-basis:100%}}'
  );
  ctx.slots.register("page", createPage(ctx));
}
